### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zmwangx** [SNH48Live/2017-recap#1]
- [x] Batch up SVG to PNG conversion. Do everything on one webpage.
- [ ] Credit snh48club.com.
- [ ] Show a three-digit index before each performance in `performances.svg`.
- [ ] Note the fact that 袁丹妮 and 冯晓菲 are only counted in their respective original team when generating the team stats. 
- [x] Add scatter plots (team vs count, <s>and generation vs count</s>).
- [ ] At the end of year, note the top attendees of regular performances in each team in the report (info printed by `generate`).
- [ ] Add notes to the beginning of recap.html, including an explicit copyright and license statement.
- [ ] Maybe setting CSS `box-sizing` will make the SVG sizes more consistent across browsers?
- [x] **Use Headless Chrome to automate the svg to png process.** Maybe the official [Puppeteer](https://github.com/GoogleChrome/puppeteer) API could help. See also [a list of other Chrome automation libraries](https://medium.com/@kensoh/chromeless-chrominator-chromy-navalia-lambdium-ghostjs-autogcd-ef34bcd26907).
- [ ] Zipped SVG pack and PNG pack (as GitHub release artifacts).
- [ ] More detailed README.
- [ ] Check how the SVGs look in Windows.
